wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.10
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717156097
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 75
      - 83
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 75
      - 83
      3:
      - 13
      - 15
      - 23
      4: 3.9.10
      5: 0.17.0
      6: 4.41.2
      8:
      - 5
      13: linux-x86_64
